dist: trusty
sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "7"
cache: yarn
install:
  - yarn
script:
  - yarn lint:prettier
  - yarn lint; true
  - yarn testrpc > /dev/null &
  - yarn test
  - yarn test:coverage
